
/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */
#pragma once


#pragma once

#define GDK_PIXBUF_USE_GIO_MIME 1

#cmakedefine GETTEXT_PACKAGE               "@GETTEXT_PACKAGE_STRING@"

#define HAVE_BIND_TEXTDOMAIN_CODESET 1

#define HAVE_LRINT 1

#cmakedefine HAVE_PROGRESSIVE_JPEG

#define HAVE_ROUND 1

#define HAVE_SETRLIMIT 1

#cmakedefine HAVE_SIGSETJMP

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_UNISTD_H 1

#define OS_LINUX 1

#cmakedefine USE_GMODULE

#define _GDK_PIXBUF_EXTERN __attribute__((visibility("default"))) extern


